### PR TITLE
Add a project Code of Conduct

### PR DESCRIPTION
**Pull request by hueniverse**
We are lacking a clear Code of Conduct. This is my initial attempt. Please review and post comments. The goal is to optimize for participation, not for freedom of speech. No one is forced to participate here and given that this is an open source project published under a liberal license, you are always free to fork and create the community you want to have instead.

### CODE REVIEW

**Comment by HankMcCoy** [comment]
Love it.

Minor nitpick, I'm not really sure what you mean by the word "authentic" in the sentence, "Participate in an authentic and active way". At a glance it seems like a hard thing to measure.

**Comment by Marsup** [comment]
@HankMcCoy I hope I'm paraphrasing here, would "truthful" be better ?

**Comment by HankMcCoy** [comment]
@Marsup, oh yeah, truthful makes way more sense to me. That's a much more clearly definable binary.

**Comment by jedireza** [comment]
Thank you for adding this.

**Comment by devinivy** [comment]
I've recently learned (concretely) that certain methods of argument/decision-making in and of themselves do hinder participation– at times potential community members will choose not to engage due to aggressive modes of communication.  This was a noticeable theme in peoples stories this year at nodeconf.

**Comment by AdriVanHoudt** [comment]
Yeah `authentic` seems vague agree.
Who is in the committee? 
`Deliberate following online`  I know this is meant as some form of stalking but Twitter popt right in my head, maybe clarify it more, or am I misreading it?

**Comment by AdriVanHoudt** [comment]
Ok just saw https://github.com/hapijs/contrib/issues/36 to form the committee :P

**Comment by mark-bradshaw** [comment]
I assume that as part of the consequences of a CoC violation, removal as a lead maintainer is an option.  The governance doc, however, says a lead maintainer cannot be removed.  If this is changing we need to remember to update the governance doc to note that a lead maintainer may be removed.  I think we should also spell out exactly how that process would work.  Unanimous decision of the CoC committee?

**Comment by nlf** [comment]
i agree with @mark-bradshaw, that is definitely something that should be addressed

**Comment by hueniverse** [comment]
No, you can't remove a lead maintainer, period.

You can fork and kick it our of the project and we already have a process for that.

**Comment by AdriVanHoudt** [comment]
@hueniverse does this translate into some form of immunity for lead maintainers?

**Comment by danielb2** [comment]
I don't see it as an immunity. As stated, the process for dealing with it is forking and kicking out. Ultimately you can't (and should not) try to control people. You can however distance yourself from them.

**Comment by mark-bradshaw** [comment]
In the end it doesn't really matter too much.  Eran has indicated in #36 that his intent is to glom onto a node committee to cover conduct, though it seems that this would need to be a consensus decision of the group.  I would like to know more about the proposed committee and the rules under which it functions.  Does anyone know any more about this?

**Comment by AdriVanHoudt** [comment]
@danielb2 yeah I don't quite get the fork thing, does the maintainer need to fork or?

**Comment by jedireza** [comment]
At the last NodeConf I joined the Diversity WG. I suspect ideas will become more concrete during the next contributor summit. You may want to follow [the thread that Eran started the other day](https://github.com/nodejs/diversity/issues/2) related to this.

The summary of the NodeConf talks can be found here (for now): https://github.com/nodejs/diversity/pull/1

**Comment by hueniverse** [comment]
If a lead maintainer is found to be in violation of the CoC and refuses to correct their ways, the module they lead will be removed from the hapi.js organization and any internal dependencies will be replaced by a fork of the module. The fork will get a new lead.

**Comment by AdriVanHoudt** [comment]
Although I don't see the reason to fork when the person is removed from the
organization I am confident the hapi community and "leadership" is mature
enough to handle the situation when it would come up. Still liking the
initiative very much!

**Comment by hueniverse** [comment]
@AdriVanHoudt the project is moved to another GitHub org, but retains the owner as well as the npm owner. That's the FL in BDFL.

**Comment by AdriVanHoudt** [comment]
@hueniverse I see, where does this BDFL come from? part of the license or?

**Comment by hueniverse** [comment]
From the governance model. Benevolent Dictator For Life.

**Comment by AdriVanHoudt** [comment]
I see, thanks for the explanation!

**Pull request merged**
