### PR TITLE
Add sponsorship policy

### PR DESCRIPTION
**Pull request by hueniverse**
This document provides an outline for obtaining module sponsorship and giving recognition to companies supporting the hapi.js ecosystem. The goal is to provide a clear list of benefits and guidelines so that sponsorships are handled fairly and equally.

### CODE REVIEW

**Comment by connor4312** [comment]
I think is really neat idea, in large part because it may make companies willing invest more resources in supporting open source software. I'm not sure what the benefit is in limiting to a single sponsor at once -- but I agree that short term (<1 sponsors) should be avoided.

**Comment by Marsup** [comment]
How would you settle which company gets the sponsorship if you have several ? The highest bidder ?

**Comment by connor4312** [comment]
What's the need to give any single company a sponsorship?

**Comment by hueniverse** [comment]
@Marsup if you are going to open it up to anyone for a price, I would just create a waiting list. I doubt this will be an issue and if the list gets too long, you under priced it. Best thing is to open it up and see who shows up and what they are comfortable paying and go from there.

**Comment by cmfatih** [comment]
Another idea would be using a donation model ( via Gratipay (formerly Gittip), Bountysource, etc ) and changing sponsor(s) every month base on donation/contribution.

**Comment by hueniverse** [comment]
@cmfatih if you are going to use something like that, it would be hard to figure out who to list as the sponsor. In that case you should just link to the page on the payment service for full list of who gave what and skip this policy.

**Comment by hueniverse** [comment]
Added a warning about legal/tax impact.

**Pull request merged**
